<?php

/**
 * @file
 * Global Override module
 *
 * @ingroup global
 */

/**
 * Implements hook_menu().
 *
 * @see hook_menu()
 */
function global_menu() {
  $items = array();

  $items['admin/config/astarter'] = array(
    'title'            => variable_get('site_name', 'Drupal'),
    'description'      => t('Custom modules configuration'),
    'page callback'    => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'position'         => 'left',
    'weight'           => 99,
    'file'             => 'system.admin.inc',
    'file path'        => drupal_get_path('module', 'system'),
  );

  return $items;
}

/**
 * Use some fancy magic to get the version number... or don't.
 */
function simple_version_callback() {
  return TRUE;
}

/**
 * Implements hook_libraries_info().
 */
function global_libraries_info() {
  $libraries = array();

  $libraries['bootstrap'] = array(
    'version callback' => 'simple_version_callback',
    'name' => 'bootstrap',
    'files' => array(
      'css'  => array(
        'css/modal.css',
        // 'css/collapse.css',
        // 'css/tab.css',
        'css/base.css',
      ),
      'js'  => array(
        'js/base.js',
        'js/modal.js',
        // 'js/tab.js',
        // 'js/affix.js',
        // 'js/collapse.js',
      ),
    ),
  );

  $libraries['wow'] = array(
    'version callback' => 'simple_version_callback',
    'name' => 'wow',
    'files' => array(
      'css'  => array(
        'animate.css',
      ),
      'js'  => array(
        'wow.min.js',
        'animation.js',
      ),
    ),
  );

  $libraries['owl-carousel'] = array(
    'version callback' => 'simple_version_callback',
    'name' => 'owl-carousel',
    'files' => array(
      'css'  => array(
        'assets/owl.carousel.min.css',
        'assets/owl.theme.default.min.css',
      ),
      'js'  => array(
        'owl.carousel.min.js',
      ),
    ),
  );

  return $libraries;
}
