<?php

/**
 * @file
 * Clean search form
 *
 * @ingroup search_form
 */

/**
 * Implements hook_theme().
 *
 * @see hook_theme()
 */
function search_form_theme() {
  return array(
    'search_form_wrapper' => array(
      'render element'  => 'element',
    ),
  );
}

/**
 * Implements hook_preprocess_search_block_form().
 *
 * @see hook_preprocess()
 */
function search_form_preprocess_search_block_form(&$variables) {
  $variables['search_form'] = str_replace('type="text"', 'type="search"', $variables['search_form']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see hook_form()
 */
function search_form_form_search_block_form_alter(&$form, &$form_state) {
  $form['#prefix'] = '<div class="search noprint" id="search">';
  $form['#suffix'] = '</div>';
  $form['#attributes']['class'][] = 'my-0';
  $form['#attributes']['role'] = 'search';

  $form['search_block_form']['#title'] = t('Search');
  $form['search_block_form']['#title_display'] = 'invisible';
  $form['search_block_form']['#size'] = 18;

  $form['search_block_form']['#attributes']['class'][] = 'search__input';
  $form['search_block_form']['#attributes']['placeholder'] = t('Search');
  $form['search_block_form']['#attributes']['title'] = t('Enter your keywords…');

  $form['actions']['#type'] = 'submit';
  $form['actions']['#value'] = t('Ok');
  $form['actions']['#attributes']['class'][] = 'search__submit';
  $form['actions']['#attributes']['title'] = t('Search on website !sitename', array('!sitename' => variable_get('site_name')));
  $form['search_block_form']['#theme_wrappers'][] = 'search_form_wrapper';
}

function search_form_form_search_form_alter(&$form, &$form_state) {
  $form['#prefix'] = '<div class="search search--advanced noprint" id="search-advanced">';
  $form['#suffix'] = '</div>';
  $form['#attributes']['class'][] = 'my-0';
  $form['#attributes']['role'] = 'search';

  $form["basic"]['keys']['#size'] = 18;
  $form["basic"]['keys']['#attributes']['class'][] = 'search__input';
  $form["basic"]['keys']['#attributes']['placeholder'] = t('Search on website !sitename', array('!sitename' => variable_get('site_name')));
  $form['basic']['keys']['#theme_wrappers'][] = 'search_form_wrapper';

  $form['advanced']['keywords']['#prefix'] = '<div class="row"><div class="criterion criterion--keywords col-xs-12 col-sm-4">';
  $form['advanced']['type']['#prefix'] = '<div class="col-xs-12 col-sm-8"><div class="row"><div class="criterion criterion--type col-xs-12 col-sm-6">';

  if (isset($form['advanced']['language'])) {
    $form['advanced']['language']['#prefix'] = '<div class="criterion criterion--language col-xs-12 col-sm-6">';
  }

  $form['advanced']['submit']['#prefix'] = '</div><div class="row"><div class="action col-xs-12">';
  $form['advanced']['submit']['#suffix'] = '</div></div></div></div>';
}

/**
 * Implements theme_form_wrapper().
 *
 * Custom Theme function
 * Remove wrapper
 *
 * @see theme_form_wrapper()
 */
function theme_search_form_wrapper(&$variables) {

  $output = '';
  $output .= $variables['element']['#children'];
  return $output;
}
