<?php

/**
 * @file
 * Clean search form
 *
 * @ingroup search_form
 */

/**
 * Implements hook_theme().
 *
 * @see hook_theme()
 */
function search_form_theme() {
  return array(
    'search_form_wrapper' => array(
      'render element'  => 'element',
    ),
  );
}

/**
 * Implements hook_preprocess_search_block_form().
 *
 * @see hook_preprocess()
 */
function search_form_preprocess_search_block_form(&$variables) {
  $variables['search_form'] = str_replace('type="text"', 'type="search"', $variables['search_form']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see hook_form()
 */
function search_form_form_search_block_form_alter(&$form, &$form_state, $form_id) {
  $form['#prefix'] = '<div class="search noprint" id="search">';
  $form['#suffix'] = '</div>';
  $form['#attributes']['class'][] = 'mvn';
  $form['#attributes']['role'] = 'search';

  $form['search_block_form']['#title'] = t('Search');
  $form['search_block_form']['#title_display'] = 'invisible';
  $form['search_block_form']['#size'] = 20;

  $form['search_block_form']['#attributes']['class'][] = 'search__input';
  $form['search_block_form']['#attributes']['placeholder'] = t('Search');
  $form['search_block_form']['#attributes']['title'] = t('Enter your keywords…');

  $form['actions']['#type'] = 'submit';
  $form['actions']['#value'] = t('Search');
  $form['actions']['#attributes']['class'][] = 'search__submit';
  $form['actions']['#attributes']['title'] = t('Search on website !sitename', array('!sitename' => variable_get('site_name')));
  $form['search_block_form']['#theme_wrappers'][] = 'search_form_wrapper';
}

/**
 * Implements theme_form_wrapper().
 *
 * Custom Theme function
 * Remove wrapper
 *
 * @see theme_form_wrapper()
 */
function theme_search_form_wrapper(&$variables) {

  $output = '';
  $output .= $variables['element']['#children'];
  return $output;
}
