<?php

/**
 * @file
 * Created block for socialworks
 *
 * @ingroup socialworks
 */

/**
 * Implements hook_menu().
 *
 * @see hook_menu()
 */
function socialworks_menu() {
  $items = array();

  $items['admin/config/astarter/socialworks'] = array(
    'title'            => t('RSALC Profile'),
    'description'      => t('Add socials links to socials profiles'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('socialworks_form'),
    'access arguments' => array('access administration pages'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'socialworks.pages.inc',
  );

  return $items;
}


/**
 * Implements hook_preprocess_block().
 *
 * @see hook_preprocess()
 */
function socialworks_preprocess_block(&$variables, $hook) {
  if ($variables['block_html_id'] == 'block-socialworks-socialworks') {
    array_unshift($variables['theme_hook_suggestions'], 'block__no_wrapper');
  }
}

/**
 * Implements hook_block_info().
 *
 * @see hook_block_info()
 */
function socialworks_block_info() {
  $blocks['socialworks'] = array(
    'info'       => t('[custom] socialworks'),
    'cache'      => DRUPAL_NO_CACHE,
    'status'     => TRUE,
    'region'     => 'footer',
    'weight'     => 0,
    'visibility' => BLOCK_VISIBILITY_NOTLISTED,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @see hook_block_view()
 */
function socialworks_block_view($delta = '') {
  $block = array();

  $path_module = drupal_get_path('module', 'socialworks');

  switch ($delta) {
    case 'socialworks':

      $output_language = '';
      if (module_exists('lang_dropdown') && variable_get('socialworks_language_chosse') == TRUE) {
        $block_invoke = module_invoke('lang_dropdown', 'block_view', 'language');
        $block_language = render($block_invoke['content']);
        $output_language = '<li>' . $block_language . '</li>';
      }

      if (variable_get('socialworks_email') == TRUE) {
        $output_language = '<li>' . l('<span class="fa fa-envolpe-o" aria-hidden="true"></span>', 'mailto:' + variable_get('sitecustom_email'), array(
          'html' => true
        )) . '</li>';
      }

      $social_networks_active = variable_get('socialworks_providers');
      if (count($social_networks_active) >= 2) {

        $markup[] = '<ul id="social-icons" class="list-inline social-icons mvm">';
        foreach ($social_networks_active as $key => $value) {
          if (!empty($value)) {
            $social_networks_url = variable_get('socialworks_' . $key);
            $markup[] = '<li class="social__item size-2x">' . l('<span class="icon icon-' . $key . '" aria-hidden="true"></span><span class="a11y">' . $value . '</span>', $social_networks_url, array(
              'attributes' => array(
                'title' => t('Follow !sitename on !network (new window).', array('!sitename' => variable_get('site_name'), '!network' => ucfirst($value))),
                'class' => array('social__link'),
                'rel' => array('external')
              ),
              'html' => TRUE
            )) . '</li>';
          }
        }
        $markup[] = $output_language;
        $markup[] = '</ul><p class="mtm"><small>' . t('Copyright © !year !sitename', array('!year' => date('Y'), '!sitename' => variable_get('site_name'))) . '</small></p>';
      }

      $block['content']['#markup'] = implode('', $markup);
      $block['content']['#attached']['data']['css'][] = drupal_add_css($path_module . '/css/socialworks.css');

      break;
  }
  return $block;
}
