<?php

/**
 * @file
 * Link to user account
 *
 * @ingroup account
 */

function scrolltotop_init() {
  $module_path = drupal_get_path('module', 'scrolltotop');
  if (!path_is_admin(current_path())) {
    drupal_add_css($module_path . '/scrolltotop.css', array(
      'group'      => CSS_DEFAULT,
      'every_page' => TRUE
    ));
    drupal_add_js($module_path . '/scrolltotop.js');
    drupal_add_js(array(
      'scrolltotop' => array(
        'label'  => t('Back to top'),
        'icon'   => 'fa-chevron-up',
        'offset' => 300)
    ), 'setting');
  }
}
