<?php

/**
 * @file
 * Link to user account
 *
 * @ingroup account
 */

function scrolltotop_init() {
  if (!path_is_admin(current_path())) {
    drupal_add_css(drupal_get_path('module', 'scrolltotop') . '/scrolltotop.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
    drupal_add_js(drupal_get_path('module', 'scrolltotop') . '/scrolltotop.js');
    drupal_add_js(array(
      'scrolltotop' => array('label' => t('Back to top'), 'icon' => 'arrow-up', 'offset' => 300)), 'setting');
  }
}
